image: node:16.16.0

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: test
  steps:
    - step: &Code-quality-step
        name: Run code quality
        script:
          - npm install
          - npm run lint
    - step: &Build-step
        name: Run build
        script:
          - npm install
          - npm run build
    - step: &Test-step
        name: Run tests
        script:
          - npm install
          - npm run migration:run:test
          - npm run test
        services:
          - postgres
    - step: &Dev-deploy-step
        name: Run deploy to dev server
        deployment: Dev
        trigger: manual
        script:
          - pipe: atlassian/ssh-run:0.4.1
            variables:
              SSH_USER: $DEV_SSH_USER
              SERVER: $DEV_SERVER
              PORT: $DEV_PORT
              MODE: 'script'
              COMMAND: 'deploy.sh'
              ENV_VARS: >-
                DEPLOYMENT_ENVIRONMENT=${BITBUCKET_DEPLOYMENT_ENVIRONMENT}
                DEPLOYMENT_BRANCH=${BITBUCKET_BRANCH}
                DEPLOYMENT_PATH=${BITBUCKET_REPO_SLUG}
              EXTRA_ARGS: '-o StrictHostKeyChecking=no'
pipelines:
  default:
    - step: *Code-quality-step
    - step: *Build-step
    - step: *Test-step
    - step: *Dev-deploy-step
  branches:
    develop:
      - step: *Code-quality-step
      - step: *Build-step
      - step: *Test-step
      - step:
          name: Run deploy to staging
          deployment: staging
          script:
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: $STAGING_SSH_USER
                SERVER: $STAGING_SERVER
                PORT: $STAGING_PORT
                MODE: 'script'
                COMMAND: 'deploy.sh'
                ENV_VARS: >-
                  DEPLOYMENT_ENVIRONMENT=${BITBUCKET_DEPLOYMENT_ENVIRONMENT}
                  DEPLOYMENT_BRANCH=${BITBUCKET_BRANCH}
                  DEPLOYMENT_PATH=${BITBUCKET_REPO_SLUG}
                EXTRA_ARGS: '-o StrictHostKeyChecking=no'
      - step: *Dev-deploy-step
    master:
      - step: *Code-quality-step
      - step: *Build-step
      - step: *Test-step
      - step:
          name: deployment-production
          deployment: 'production'
          script: # Modify the commands below to build your repository.
            - npm install
            - npm run build
#            - pipe: atlassian/sftp-deploy:0.5.6
#              variables: &sftp-variables
#                USER: 'bitbucket'
#                SERVER: 'staging.apis.tdg-invent.io'
#                REMOTE_PATH: '/var/www/folder'
#                NODE_ENV: 'production'
#                LOCAL_PATH: 'dist/*'
#            - ssh bitbucket@staging.apis.tdg-invent.io 'cd /var/www/folder && . ./bin/provision.sh --staging'
