version: '3.7'

services:
  auth_redis:
    container_name: auth_redis
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=admin
      - REDIS_REPLICATION_MODE=master
    networks:
      - redis
      - default
networks:
  redis:
    name: redis
