version: '3.7'

services:
  auth:
    container_name: auth
    build:
      context: .
      target: development
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 50003:50003
#      - 9229:9229
    # these two command keeps apline container running
    stdin_open: true # docker run -i
    tty: true # docker run -t
    networks:
      - metascape
      - default
    depends_on:
      - auth_db
      - redis-auth-test
networks:
  metascape:
    name: metascape
