version: '3.7'

services:
  auth:
    container_name: auth
    build:
      context: .
      target: production
      dockerfile: ./docker/Dockerfile
    networks:
      - metascape
      - default
networks:
  metascape:
    name: metascape
