version: '3.7'

services:
  auth_db:
    container_name: auth_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - database
      - default
volumes:
  data:
networks:
  database:
    name: database
