export const PARAMETERS = {
  NODE_ENV: 'NODE_ENV',
  AUTH_API_GRPC_URL: 'AUTH_API_GRPC_URL',
  USER_API_GRPC_URL: 'USER_API_GRPC_URL',
  WALLET_API_GRPC_URL: 'WALLET_API_GRPC_URL',
  JWT_SECRET: 'JWT_SECRET',
  JWT_AUTH_PRIVATE_KEY: 'JWT_AUTH_PRIVATE_KEY',
  JWT_AUTH_PUBLIC_KEY: 'JWT_AUTH_PUBLIC_KEY',
  JWT_AUTH_EXPIRES_IN: 'JWT_AUTH_EXPIRES_IN',
  JWT_REFRESH_PRIVATE_KEY: 'JWT_REFRESH_PRIVATE_KEY',
  JWT_REFRESH_PUBLIC_KEY: 'JWT_REFRESH_PUBLIC_KEY',
  JWT_REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',
  JWT_ALGORITHM: 'JWT_ALGORITHM',
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USER: 'DB_USER',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_NAME: 'DB_NAME',
};

export default PARAMETERS;
