export const PARAMETERS = {
  NODE_ENV: 'NODE_ENV',
  AUTH_API_GRPC_URL: 'AUTH_API_GRPC_URL',
  USER_API_GRPC_URL: 'USER_API_GRPC_URL',
  WALLET_API_GRPC_URL: 'WALLET_API_GRPC_URL',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',
  JWT_PRIVATE_KEY: 'JWT_PRIVATE_KEY',
  JWT_PUBLIC_KEY: 'JWT_PUBLIC_KEY',
  JWT_ALGORITHM: 'JWT_ALGORITHM',
};

export default PARAMETERS;
